package edge

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
	"unicode/utf8"
)

var candidateIDPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$`)

// Generator creates one additive edge-test suite from the exact Request
// bytes. It must stop work when ctx is cancelled and use the supplied shared
// recipe without weakening the approved acceptance source.
type Generator interface {
	Generate(context.Context, []byte, Recipe) ([]byte, error)
}

// Runner executes one generated suite against a candidate. Implementations
// must supervise their process, enforce ctx, stage source outside the
// candidate tree, and capture candidate-tree identities around execution.
type Runner interface {
	Run(context.Context, RunRequest) (Observation, error)
}

// RunRequest describes one generated suite execution. Suite source is an
// exact, immutable copy; SuiteOwnerID is the rung that produced it.
type RunRequest struct {
	CandidateID  string
	SuiteOwnerID string
	Workspace    string
	Suite        Suite
	Recipe       Recipe
}

// Suite contains exact generated bytes and their stable identity.
type Suite struct {
	Source []byte
	SHA256 string
}

// Observation contains runner facts. A suite passes only when it discovered
// at least one test, all tests passed, none were skipped, the process exited
// zero without timeout/unavailability, and the candidate tree stayed fixed.
type Observation struct {
	ExitStatus   *int
	TimedOut     bool
	Unavailable  bool
	TotalTests   int
	PassedTests  int
	FailedTests  int
	SkippedTests int
	TreeBefore   string
	TreeAfter    string
	OutputTail   []byte
}

type Status string

const (
	StatusSkipped Status = "skipped"
	StatusPassed  Status = "passed"
	StatusFailed  Status = "failed"
	StatusStopped Status = "stopped"
)

type Failure string

const (
	FailureInvalidRequest    Failure = "invalid_request"
	FailureGenerator         Failure = "generator_failed"
	FailureGenerationLimit   Failure = "generation_timeout"
	FailureSuiteInvalid      Failure = "suite_invalid"
	FailureRunner            Failure = "runner_failed"
	FailureRunnerLimit       Failure = "runner_timeout"
	FailureRunnerUnavailable Failure = "runner_unavailable"
	FailureNoTests           Failure = "no_tests"
	FailureTestsFailed       Failure = "tests_failed"
	FailureTreeMutated       Failure = "tree_mutated"
	FailureObservation       Failure = "observation_invalid"
	FailureCancelled         Failure = "cancelled"
)

// Outcome is the generated-check result. Required remains true for every
// attempted edge run, including invalid output and infrastructure failures;
// callers cannot treat a failed required check as if edge tests were disabled.
type Outcome struct {
	Required    bool
	Status      Status
	Failure     Failure
	Suite       Suite
	Observation *Observation
}

// Passed reports whether the complete required edge suite passed.
func (o Outcome) Passed() bool {
	if !o.Required {
		return o.Status == StatusSkipped && o.Failure == ""
	}
	if o.Status != StatusPassed || o.Failure != "" || !validateSuite(o.Suite, SharedRecipe()) || o.Observation == nil {
		return false
	}
	failure, stopped := assess(*o.Observation, SharedRecipe())
	return failure == "" && !stopped
}

// CanLand keeps ordinary approved acceptance mandatory and adds the edge
// outcome as a separate conjunctive requirement.
func (o Outcome) CanLand(approvedAcceptancePassed bool) bool {
	return approvedAcceptancePassed && o.Passed()
}

// ProbeRequest enables or skips edge generation for one candidate.
type ProbeRequest struct {
	Enabled     bool
	CandidateID string
	Workspace   string
	Request     []byte
}

// Controller runs generated checks for one candidate. A generation, runner,
// timeout, malformed observation, or test failure never produces a pass.
type Controller struct {
	generator Generator
	runner    Runner
	recipe    Recipe
}

func New(generator Generator, runner Runner) (*Controller, error) {
	if generator == nil || runner == nil {
		return nil, errors.New("edge: generator and runner are required")
	}
	return &Controller{generator: generator, runner: runner, recipe: SharedRecipe()}, nil
}

// Probe generates tests from the byte-exact Request and executes them before
// landing. A disabled probe performs no generation or runner calls.
func (c *Controller) Probe(ctx context.Context, request ProbeRequest) Outcome {
	if !request.Enabled {
		return Outcome{Status: StatusSkipped}
	}
	out := Outcome{Required: true, Status: StatusStopped}
	if c == nil || c.generator == nil || c.runner == nil || ctx == nil || !validCandidate(request.CandidateID, request.Workspace) || !validRequest(request.Request, c.recipe) {
		out.Failure = FailureInvalidRequest
		return out
	}
	if err := ctx.Err(); err != nil {
		out.Failure = FailureCancelled
		return out
	}

	generationCtx, cancelGeneration := context.WithTimeout(ctx, c.recipe.GenerationTimeout)
	source, err := c.generator.Generate(generationCtx, append([]byte(nil), request.Request...), c.recipe)
	generationErr := generationCtx.Err()
	cancelGeneration()
	if err != nil || generationErr != nil {
		if errors.Is(ctx.Err(), context.Canceled) || errors.Is(ctx.Err(), context.DeadlineExceeded) {
			out.Failure = FailureCancelled
		} else if errors.Is(generationErr, context.DeadlineExceeded) {
			out.Failure = FailureGenerationLimit
		} else {
			out.Failure = FailureGenerator
		}
		return out
	}

	suite, err := newSuite(source, c.recipe)
	if err != nil {
		out.Status = StatusFailed
		out.Failure = FailureSuiteInvalid
		return out
	}
	out.Suite = suite
	observation, failure, stopped := runSuite(ctx, c.runner, RunRequest{
		CandidateID:  request.CandidateID,
		SuiteOwnerID: request.CandidateID,
		Workspace:    request.Workspace,
		Suite:        cloneSuite(suite),
		Recipe:       c.recipe,
	})
	if observation != nil {
		out.Observation = observation
	}
	if failure != "" {
		out.Failure = failure
		if stopped {
			out.Status = StatusStopped
		} else {
			out.Status = StatusFailed
		}
		return out
	}
	out.Status = StatusPassed
	return out
}

func validRequest(request []byte, recipe Recipe) bool {
	return len(request) > 0 && len(request) <= recipe.MaxRequestBytes && utf8.Valid(request) && !strings.ContainsRune(string(request), '\x00')
}

func validCandidate(id, workspace string) bool {
	return candidateIDPattern.MatchString(id) && filepath.IsAbs(workspace) && filepath.Clean(workspace) == workspace && !strings.ContainsRune(workspace, '\x00')
}

func newSuite(source []byte, recipe Recipe) (Suite, error) {
	if len(source) == 0 || len(source) > recipe.MaxSuiteBytes || !utf8.Valid(source) || strings.ContainsRune(string(source), '\x00') {
		return Suite{}, errors.New("edge: generated suite is empty, oversized, or invalid text")
	}
	copySource := append([]byte(nil), source...)
	digest := sha256.Sum256(copySource)
	return Suite{Source: copySource, SHA256: hex.EncodeToString(digest[:])}, nil
}

func validateSuite(suite Suite, recipe Recipe) bool {
	if len(suite.Source) == 0 || len(suite.Source) > recipe.MaxSuiteBytes || !utf8.Valid(suite.Source) || strings.ContainsRune(string(suite.Source), '\x00') {
		return false
	}
	digest := sha256.Sum256(suite.Source)
	return suite.SHA256 == hex.EncodeToString(digest[:])
}

func runSuite(ctx context.Context, runner Runner, request RunRequest) (*Observation, Failure, bool) {
	if ctx == nil || runner == nil || !validCandidate(request.CandidateID, request.Workspace) || !candidateIDPattern.MatchString(request.SuiteOwnerID) || !validateSuite(request.Suite, request.Recipe) {
		return nil, FailureSuiteInvalid, false
	}
	if err := ctx.Err(); err != nil {
		return nil, FailureCancelled, true
	}
	runCtx, cancel := context.WithTimeout(ctx, request.Recipe.TestTimeout)
	observation, err := runner.Run(runCtx, cloneRunRequest(request))
	runErr := runCtx.Err()
	cancel()
	if err != nil || runErr != nil {
		if errors.Is(ctx.Err(), context.Canceled) || errors.Is(ctx.Err(), context.DeadlineExceeded) {
			return nil, FailureCancelled, true
		}
		if errors.Is(runErr, context.DeadlineExceeded) {
			return nil, FailureRunnerLimit, true
		}
		return nil, FailureRunner, true
	}
	observation.OutputTail = boundedTail(observation.OutputTail, request.Recipe.MaxOutputTailBytes)
	copyObservation := cloneObservation(observation)
	failure, stopped := assess(observation, request.Recipe)
	return &copyObservation, failure, stopped
}

func assess(observation Observation, recipe Recipe) (Failure, bool) {
	switch {
	case observation.TimedOut:
		return FailureRunnerLimit, true
	case observation.Unavailable || observation.ExitStatus == nil:
		return FailureRunnerUnavailable, true
	case observation.TotalTests < 0 || observation.PassedTests < 0 || observation.FailedTests < 0 || observation.SkippedTests < 0 || observation.TotalTests > recipe.MaxTests:
		return FailureObservation, true
	case observation.TotalTests == 0:
		return FailureNoTests, false
	case observation.PassedTests+observation.FailedTests+observation.SkippedTests != observation.TotalTests:
		return FailureObservation, true
	case observation.TreeBefore == "" || observation.TreeAfter == "":
		return FailureObservation, true
	case observation.TreeBefore != observation.TreeAfter:
		return FailureTreeMutated, false
	case *observation.ExitStatus != 0 || observation.FailedTests != 0 || observation.SkippedTests != 0 || observation.PassedTests != observation.TotalTests:
		return FailureTestsFailed, false
	default:
		return "", false
	}
}

func boundedTail(value []byte, max int) []byte {
	if max <= 0 {
		return nil
	}
	if len(value) > max {
		value = value[len(value)-max:]
	}
	return append([]byte(nil), value...)
}

func cloneSuite(value Suite) Suite {
	return Suite{Source: append([]byte(nil), value.Source...), SHA256: value.SHA256}
}

func cloneObservation(value Observation) Observation {
	clone := value
	if value.ExitStatus != nil {
		status := *value.ExitStatus
		clone.ExitStatus = &status
	}
	clone.OutputTail = append([]byte(nil), value.OutputTail...)
	return clone
}

func cloneRunRequest(value RunRequest) RunRequest {
	value.Suite = cloneSuite(value.Suite)
	return value
}

func (o Outcome) String() string {
	return fmt.Sprintf("edge outcome{required=%t status=%q failure=%q}", o.Required, o.Status, o.Failure)
}
